### ISSUE TITLE
[ compat ] Build error with current Idris HEAD

### ISSUE THREAD

**Issue by stefan-hoeck** [joelberkeley/spidr#345]
Currently, spidr does not build, probably due to recent fixes in the Idris termination checker. In order to continue getting nightly builds for the pack collection, I disabled (commented-out) spidr and a couple of other libraries in `collections/HEAD.db` for the time being. Feel free to uncomment it again, once spidr builds again. You can also just comment on or close this issue, in which case I'll reenable spidr for you.

**Comment by joelberkeley** [comment]
I'm not sure I understand how this works. Are people able to install the previously working collections including spidr?

And how do I test this? If I
```bash
$ pack update
$ pack update-db
```
then
```bash
$ pack install spidr.ipkg
```
locally, it builds successfully

**Comment by stefan-hoeck** [comment]
When I wrote this issue, there was no pack collection with the latest compiler available, because the collection could no longer be built due to failing packages,, so you'd have to install it manually, for instance by adding the following line to your global `pack.toml` file and the running `pack --bootstrap install spidr.ipgk`:

```toml
[idris2]

commit     = "2e9c7fb8b587ea2734f0c62c64aa975c4cf95489"
```

Now, you can just run `pack switch latest` (`pack update` will just update the pack application itself, and `pack update-db` will download the latest pack collections without setting one of them as your default), followed by `pack typecheck spidr.ipkg`.

**Comment by joelberkeley** [comment]
ok thanks. And if I don't do this, will people still be able to install spidr with older versions of Idris?

**Comment by stefan-hoeck** [comment]
> ok thanks. And if I don't do this, will people still be able to install spidr with older versions of Idris?

Yes, spidr is part of pack collections up to and including `nightly-230206`.

**Comment by joelberkeley** [comment]
done
